### ISSUE TITLE
抓个虫

### ISSUE THREAD

**Issue by kanonmelodis** [reusu/FFXIVChnTextPatch#1]
国服版

1.已完成列表任务名不对应
2.雇员探险-自由探险选项文本不对应

**Comment by reusu** [comment]
吐槽：莫名其妙加了一个奇妙的东西 ，算了不管了

之所以会存在LZ说的情况
因为SE的版本差异文件内容格式不一致导致的
等国服4.1可能就正常了
暂时不做修复处理

如果到时候还这样可能会给一个处理方案
谢谢反馈
