### ISSUE TITLE
汉化为繁体中文后，部分操作引起程式崩溃

### ISSUE THREAD

**Issue by steve75918** [reusu/FFXIVChnTextPatch#12]
在繁体中文的状态下，以下两种操作会引发程式异常

1. 调查他人装备
2. 与军团人事负责人对话（筹备任务）

另外无论使用繁中或简中，都无法进入优雷卡，与 NPC 对话后只会卡住，没有任何反应，也无法进行其他操作，不会看到任何对话框，目前只能从工作管理员关闭程式

主程式版本：4.5（全新安装）
汉化程式版本：C1.0.1

上述几点是比较影响游戏进行的部分，期待早日修复，感谢 m(_ _)m

**Comment by reusu** [comment]
已修复
