### ISSUE TITLE
Custom Translation//自定义翻译

### ISSUE THREAD

**Issue by xDarkOne** [reusu/FFXIVChnTextPatch#13]
Hello.
I am interested in custom translation for FFXIV. I wanted to make Russian translation. But I have problems with exd files, i cant pack it. And I've found your project, but not sure, did you unpack and pack these files or you used CH version of FFXIV.
Tell me please if it's possible.
I translated this text with Google Translate, if it will help you to understand me.

你好。
我对FFXIV的自定义翻译感兴趣。 我想做俄语翻译。 但我有exd文件的问题，我不能打包它。 我找到了你的项目，但不确定，你是否打开包装并打包这些文件，或者你使用的是FF版的FFXIV。
请告诉我，如果可能的话。
我将此文本翻译成谷歌翻译，如果它能帮助你理解我。

**Comment by reusu** [comment]
理论上说，这个项目的核心代码是支持任何语言的翻译导入
不过，最前提是需要解决字库问题
游戏的字库是储存在由fdt文件指向tex位图文件中
我不确定这个游戏是否支持俄语输入
我将此文本翻译成谷歌翻译，如果它能帮助你理解我

In theory, the core code of this project is to support translation import in any language.
However, the most premise is that you need to solve the font problem.
The font of the game is stored in the tex bitmap file pointed to by the fdt file.
I am not sure if this game supports Russian input.
I translated this text with Google Translate, if it will help you to understand me.

**Comment by reusu** [comment]
我在游戏中尝试了以下命令
/echo Россия— священная наше держава
结果俄语是可以正常显示的
所以理论上来说是可以做到俄语化的

I tried the following command in the game.
/echo Россия— священная наше держава
The result is that Russian can be displayed normally.
So in theory, it can be Russianized.

**Comment by xDarkOne** [comment]
Thank you for your reply, I'll try to do something :)

谢谢你的回复，我会尝试做点什么 :)

**Comment by xDarkOne** [comment]
Where can i talk with you and get some assistant maybe with core code?
我可以在哪里与您交谈并获得一些助手，可能还有核心代码？

**Comment by xDarkOne** [comment]
Hello again, today i tried to inject into memory and change it and it worked perfectly, can you help me to implement russian translation into game? Pls pls pls :3

**Comment by reusu** [comment]
email： admin@yumao.name
this issuse will be closed :)
