### ISSUE TITLE
不知道4.2_7版修复了这个BUG没

### ISSUE THREAD

**Issue by wingchaos** [reusu/FFXIVChnTextPatch#14]
之前的一直都存在一个问题是。大多职业任务（尤其是70级的职业任务）要过剧情进入战斗前，点击NPC那，UI全不见了，不会弹出确定或者取消 的UI.只能关游戏切回英文打。

**Comment by bufordliu** [comment]
此问题仍然存在，4.15剧情战斗，对美神的战斗前也存在此问题
