### ISSUE TITLE
已经成为提莫苑用户了为什么汉化显示网络连接失败

### ISSUE THREAD

**Issue by ChaselChasel** [reusu/FFXIVChnTextPatch#14]

**Comment by iiooiuy2** [comment]
買這邊會員就是用戶了嗎?  買完下載  開程式跳出 無法獲取網路數據

**Comment by KumaTai** [comment]
同樣有無法獲取網路數據的問題，是電腦端也要安裝提莫院並連接上嗎還是....?

**Comment by reusu** [comment]
连接成功后可以打开
http://ffxiv.chn.teemo.name
观察是否能打开来检查隧道是否正常建立
海外用户需要切换到海外用户模式
连接海外节点即可

**Comment by JierongFan** [comment]
http://ffxiv.chn.teemo.name我在连接提莫苑vpn后能打开这个链接，但汉化还是无法获取网络数据

**Comment by JierongFan** [comment]
如果有无法获取网络数据的情况发生，尝试在github里下载最新的汉化程序试试。

**Comment by KumaTai** [comment]
2019. 3/26測試過是可以使用的，如果有多個虛擬網卡，可以試著停用其他，讓他只剩下一個即可

**Comment by love88056** [comment]
請問一下，我也是成為用戶了，海外用戶也連接成功了，漢化程序反而找不到在哪邊
有大佬能夠教學嗎

**Comment by KumaTai** [comment]
https://github.com/reusu/FFXIVChnTextPatch/releases
