### ISSUE TITLE
我想问下如何购买汉化呢

### ISSUE THREAD

**Issue by sunnyboa** [reusu/FFXIVChnTextPatch#17]
同题，如何成为会员呢？我不是很熟悉这个网站

**Comment by haojunsui** [comment]
https://www.teemo.link

**Comment by sunnyboa** [comment]
我去了。。是下个虚拟网卡么？

**Comment by KumaTai** [comment]
1. 下載並安裝虛擬網卡
2. 成為提摩苑會員，並購買時數
3. 使用提摩苑連線客戶端登入帳號建立連線
4. 開啟漢化程式時才能通過驗證，如沒做前面三步驟，則會出現驗證失敗訊息。

如上述步驟有誤，請任意指出

**Comment by nnbear37** [comment]
我今天購買了會員，請問一下它是每次使用都得續費嗎？還是一次性的呢？

**Comment by reusu** [comment]
> 我今天購買了會員，請問一下它是每次使用都得續費嗎？還是一次性的呢？

每次使用都需要建立好连接
至于购买使用方法@KumaTai 说的很清楚

**Comment by Sharnes** [comment]
您好，想請問如何購買會員呢?
我下載並安裝了虛擬網卡，執行後顯示要登入使用者帳密
去了https://www.teemo.link找不到可以購買/加入會員的地方
是要點企鵝群嗎? 如果沒有QQ有沒有其他付款方式呢?
謝謝您

**Comment by Sharnes** [comment]
您好，剛至https://www.teemo.link 註冊並使用支付寶支付完畢了
但會員登錄顯示「用户登录信息不正确」，確認帳密輸入是正確的
想詢問是會有一個入賬等待期間嗎?
還是一支付完畢就能登入呢?
謝謝您
