### ISSUE TITLE
最新漢化 item詳細內容消失

### ISSUE THREAD

**Issue by jim948kjy** [reusu/FFXIVChnTextPatch#19]
如標題  回報給漢化組~

**Comment by reusu** [comment]
请PO图

**Comment by jim948kjy** [comment]
![image](https://user-images.githubusercontent.com/48384036/55777043-498aab00-5ad1-11e9-9b88-3688749d57e9.png)
如上圖  游標在身體防具上  但沒有顯示詳細裝備素質 背包中的物品同理

**Comment by reusu** [comment]
请尝试使用简中重现问题
如果简中没有该问题的话
这个问题将归属于待处理BUG队列中

**Comment by jim948kjy** [comment]
繁簡都有這個狀況哦！兩種都測試過了

**Comment by reusu** [comment]
请使用最新版本的patch
并且使用云端还原素材
我这边测试是正常的
无法重现问题
