### ISSUE TITLE
存在问题反馈

### ISSUE THREAD

**Issue by wingchaos** [reusu/FFXIVChnTextPatch#2]
A 
#字符串替换 优先级2
 需要翻译的内容不能存在空格，否则不成功
     如：失われた都 ラバナスタ    这里的“都”跟“ラ”中间有空格。汉化失败惹。

B
#翻译表字节替换 优先级1
 再次拿“失われた都 ラバナスタ”做例子
   在工具里搜索获取后有一个如下{
 exd/quest/030/stmbdi102_03004|26|1|E3808CE5A4B1E3828FE3828CE3819FE983BD20E383A9E38390E3838AE382B9E382BFE3808DE38292E694BBE795A5|「失われた都 ラバナスタ」を攻略
}
按照您提供的方法这段“ exd/quest/030/stmbdi102_03004|26|1|”改成“exd/quest/030/stmbdi102_03004_26_1”
这样原来的“stmbdi102_03004”里面的的下滑占位符“_”就应该不生效了。希望提供解决方案。
再次感谢提供汉化。

**Comment by reusu** [comment]
A-A：
KEY中内容 空格字符请用\u0020转义 VALUE不受影响
例如=>
失われた都\u0020ラバナスタ=失落之都 测试
这个是JAVA的Configuration库的识别问题

A-B：
感谢抓虫 这部分是TOOL的搜索功能显示列出问题了
已修正 跟下划占位符的多少并无任何关系
实际上的StringCount = 2 
因为个人失误判断为了1
所以准确的内容为=>
exd/quest/030/stmbdi102_03004_26_2=5aSx6JC95LmL6YO9IOa1i+ivlQ==
导致汉化内容无法写入 ：）

#1 https://github.com/reusu/FFXIVChnTextPatch/commit/b50fcad9da65ed295b90f10222eb6b06d975851c

**Comment by reusu** [comment]
https://github.com/reusu/FFXIVChnTextPatch/commit/b50fcad9da65ed295b90f10222eb6b06d975851c

**Comment by reusu** [comment]
Fix #1

**Comment by reusu** [comment]
#1 Fix
