### ISSUE TITLE
“汉化”按钮为灰色

### ISSUE THREAD

**Issue by wingchaos** [reusu/FFXIVChnTextPatch#2]
不知道原因，可能是更新了win10最新版某个补丁吧。
现在如果汉化路径里面，000000.win32 0a0000.win32这6个文件如果是国际服的，
就会出现这个情况，汉化按钮是灰色的，不能操作。
重装系统试过也不行。4.3_5///4.3_1 _2都是酱紫。4.2_6反而没有这个情况
现在临时解决方案是，先用 国服的 这6个文件放进去，然后启动4.3_5的汉化工具，再替换回国际服的需要汉化的6个文件 - -
不知道原因。。。emmmmm

**Comment by reusu** [comment]
汉化过的客户端 检测到关键字会关闭汉化功能 防止多重汉化导致的客户端报废
