### ISSUE TITLE
提莫苑MAC端 无法连接

### ISSUE THREAD

**Issue by jqyang3108** [reusu/FFXIVChnTextPatch#21]
<img width="302" alt="屏幕快照 2019-04-23 18 18 59" src="https://user-images.githubusercontent.com/42568174/56619655-4bd22680-65f4-11e9-8796-9d38ec3ccc0e.png">
按照使用说明启动登陆客户端，无法连接。

**Comment by reusu** [comment]
请放置到应用程序文件夹运行

**Comment by jqyang3108** [comment]
感谢回复，我是把两个程序都放在应用程序里运行的。是应该另外的叫做应用程序的文件夹里吗？
<img width="678" alt="屏幕快照 2019-04-23 20 39 02" src="https://user-images.githubusercontent.com/42568174/56624677-dc663200-6607-11e9-929a-caebe6835c5f.png">

**Comment by reusu** [comment]
理论上程式在非 下载 文件夹都有权限生成配置文件，
推荐复制到应用程序 也就是/Application后运行
程序运行的时候会提示输入当前账号密码以提权运行
如果还有权限问题可以尝试直接使用root用户运行

**Comment by jqyang3108** [comment]
> 理论上程式在非 下载 文件夹都有权限生成配置文件，
> 推荐复制到应用程序 也就是/Applications后运行
> 程序运行的时候会提示输入当前账号密码以提权运行
> 如果还有权限问题可以尝试直接使用root用户运行

我尝试了在应用程序以外的文件夹和root用户运行，还是相同的错误

**Comment by reusu** [comment]
> > 理论上程式在非 下载 文件夹都有权限生成配置文件，
> > 推荐复制到应用程序 也就是/Applications后运行
> > 程序运行的时候会提示输入当前账号密码以提权运行
> > 如果还有权限问题可以尝试直接使用root用户运行
> 
> 我尝试了在应用程序以外的文件夹和root用户运行，还是相同的错误

尝试了重新下载新客户端然后链接  无法复现该错误……
请检查jdk版本是否为1.8 以及权限是否有效

**Comment by jqyang3108** [comment]
> > > 理论上程式在非 下载 文件夹都有权限生成配置文件，
> > > 推荐复制到应用程序 也就是/Applications后运行
> > > 程序运行的时候会提示输入当前账号密码以提权运行
> > > 如果还有权限问题可以尝试直接使用root用户运行
> > 
> > 
> > 我尝试了在应用程序以外的文件夹和root用户运行，还是相同的错误
> 
> 尝试了重新下载新客户端然后链接 无法复现该错误……
> 请检查jdk版本是否为1.8 以及权限是否有效
> 
> > java -version
> > java version "1.8.0_191"
> > Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
> > Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

刚刚检查过应该不是Java的问题，运行程序时也的确有输入提示让输入账号密码来提权。我也不知道是不是权限出了问题，头大ing。。。

**Comment by reusu** [comment]
> > > > 理论上程式在非 下载 文件夹都有权限生成配置文件，
> > > > 推荐复制到应用程序 也就是/Applications后运行
> > > > 程序运行的时候会提示输入当前账号密码以提权运行
> > > > 如果还有权限问题可以尝试直接使用root用户运行
> > > 
> > > 
> > > 我尝试了在应用程序以外的文件夹和root用户运行，还是相同的错误
> > 
> > 
> > 尝试了重新下载新客户端然后链接 无法复现该错误……
> > 请检查jdk版本是否为1.8 以及权限是否有效
> > > java -version
> > > java version "1.8.0_191"
> > > Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
> > > Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
> 
> 刚刚检查过应该不是Java的问题，运行程序时也的确有输入提示让输入账号密码来提权。我也不知道是不是权限出了问题，头大ing。。。

那我也有点摸不着头脑了 可以尝试：
1 安全性与隐私 - 通用 - 允许从以下位置下载的应用 - App Store 和被认可的开发者
2 安全性与隐私 - 隐私 - 完全磁盘访问权限 - 添加TeemoCDN
如果还不行的话我也没办法了 对MacOS了解不够深

**Comment by jqyang3108** [comment]
> > > > > 理论上程式在非 下载 文件夹都有权限生成配置文件，
> > > > > 推荐复制到应用程序 也就是/Applications后运行
> > > > > 程序运行的时候会提示输入当前账号密码以提权运行
> > > > > 如果还有权限问题可以尝试直接使用root用户运行
> > > > 
> > > > 
> > > > 我尝试了在应用程序以外的文件夹和root用户运行，还是相同的错误
> > > 
> > > 
> > > 尝试了重新下载新客户端然后链接 无法复现该错误……
> > > 请检查jdk版本是否为1.8 以及权限是否有效
> > > > java -version
> > > > java version "1.8.0_191"
> > > > Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
> > > > Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
> > 
> > 
> > 刚刚检查过应该不是Java的问题，运行程序时也的确有输入提示让输入账号密码来提权。我也不知道是不是权限出了问题，头大ing。。。
> 
> 那我也有点摸不着头脑了 可以尝试：
> 1 安全性与隐私 - 通用 - 允许从以下位置下载的应用 - App Store 和被认可的开发者
> 2 安全性与隐私 - 隐私 - 完全磁盘访问权限 - 添加应用程式
> 如果还不行的话我也没办法了 对MacOS了解不够深

十分感谢你的帮助，我再排查一下。

**Comment by reusu** [comment]
请尝试将程序置于桌面运行 应该可以解决问题
置于应用程序中运行会被拷贝到/private/var/folder中运行
导致没有权限生成配置文件
原因还在查询中……

**Comment by reusu** [comment]
我查看了官方的文档
应该是触发了App Translocation的沙箱保护导致的
使用浏览器下载并解压的APP会带com.apple.quarantine标记
如果你是将APP “拖” 到 应用程式的话 这个标记会一直存在
导致即使是ROOT也无权操作磁盘
但是如果你将APP “拷贝” 到应用程式的话 
那么就不会有这个问题出现了
