### ISSUE TITLE
有會員仍顯示無法讀取客戶端數據

### ISSUE THREAD

**Issue by Sharnes** [reusu/FFXIVChnTextPatch#22]
![1556101965650](https://user-images.githubusercontent.com/49665790/56653112-88b71f80-66bf-11e9-9a0c-3d888f89b83c.jpg)

您好，下載了最新釋出4/24的patch包，保持會員連接狀態跑漢化仍顯示無法讀取客戶端數據，
然而使用4/8的patch包可正常漢化，這部分有辦法怎麼解決嗎?
謝謝您

**Comment by reusu** [comment]
fixed
