### ISSUE TITLE
window版 无法获取网络数据

### ISSUE THREAD

**Issue by shiroikami00** [reusu/FFXIVChnTextPatch#25]
![微信截图_20190430195926](https://user-images.githubusercontent.com/50157802/57000724-d7aefa00-6b82-11e9-85b7-4b7aa66142fb.png)
请问这个怎么解决? 我把文件放在游戏文件里运行也不行

**Comment by originalvoid** [comment]
我也遇到相同狀況 求解

**Comment by shiroikami00** [comment]
@reusu

**Comment by shiroikami00** [comment]
麻烦解答一下 谢谢!

**Comment by reusu** [comment]
仅在链接了提莫苑的情况下才能使用汉化client，请知晓
