### ISSUE TITLE
發生錯誤

### ISSUE THREAD

**Issue by henryleeeeee** [reusu/FFXIVChnTextPatch#33]
您好!
改版後提莫苑連接狀態 :發生錯誤
一直連不上,似乎並不是網路問題
請問是否有辦法解決? 謝謝.
![Screenshot_5](https://user-images.githubusercontent.com/52327090/60354539-028cc180-99ff-11e9-9a2d-994f5ce44312.jpg)

**Comment by reusu** [comment]
海外用户请在官网选择海外用户模式
