### ISSUE TITLE
无法获取网络数据问题

### ISSUE THREAD

**Issue by KuroroTT** [reusu/FFXIVChnTextPatch#35]
你好，看了一些别人的回复
还是不理解
“仅在链接了提莫苑的情况下才能使用汉化的客户端”
是什么意思?
需要在哪里购买后才可以使用吗？

**Comment by akira0245** [comment]
买了他家的加速器才能用的意思。

**Comment by KuroroTT** [comment]
> 买了他家的加速器才能用的意思。

那应该在哪买呢？顺便问一下本人就在国外加速器还有用吗？

**Comment by jxgzs** [comment]
> > 买了他家的加速器才能用的意思。
> 
> 那应该在哪买呢？顺便问一下本人就在国外加速器还有用吗？

https://www.teemo.link/
在海外感觉汉化完了就没必要在开加速器了
