### ISSUE TITLE
找不到微信付款的

### ISSUE THREAD

**Issue by puma5566** [reusu/FFXIVChnTextPatch#40]
您好

我是台灣用戶 

找不到微信付款的方式(只有看到支付寶)

可否提供

謝謝

**Comment by moshaocc** [comment]
你是说提莫苑加速器的微信付款码吗

puma5566 <notifications@github.com>于2019年7月23日 周二09:56写道：

**Comment by puma5566** [comment]
我是要買FF14漢化的

**Comment by jxgzs** [comment]
> 我是要买FF14汉化的

登陆提莫苑 登入你的账号密码，点击左上角用户，再点击续约，选择你的时常，选择你的支付方式，有支付宝和微信。

**Comment by puma5566** [comment]
我有看到了
謝謝您的幫忙
我再試試看
謝謝

**Comment by puma5566** [comment]
- 

-

**Comment by hydesthydest** [comment]
點來點去還是不知道怎麼續約QQ......有辦法在解釋清楚一點嗎 真的感謝了

登陆提莫苑 登入你的账号密码，点击左上角用户，再点击续约，选择你的时常，选择你的支付方式，有支付宝和微信。
