### ISSUE TITLE
已是會員，也連結成功 但無漢化

### ISSUE THREAD

**Issue by puma5566** [reusu/FFXIVChnTextPatch#41]
![11](https://user-images.githubusercontent.com/53225581/61805459-67093800-ae68-11e9-9366-8c2c8dce0ded.JPG)

不好意思

我今天剛付款了，也已連結上了

但打開遊戲還是英文的耶

請問要如何著手漢化呢?

謝謝

**Comment by puma5566** [comment]
補充一下
我有使用 FFXIVChnTextPatch_WIN 進行漢化

有下載資料 也有安裝寫下載成功
但是近遊戲還是英文的

不知道還有哪邊要設定的
謝謝

**Comment by jim948kjy** [comment]
是以日文客戶端進行漢化的 在登入介面那邊就要切成日文客戶端來登入

**Comment by moshaocc** [comment]
你先连上加速器，再打开汉化软件进行汉化

puma5566 <notifications@github.com>于2019年7月24日 周三11:56写道：

**Comment by puma5566** [comment]
了解 可以用了
謝謝各位幫忙
