### ISSUE TITLE
實在找不到如何用微信付款，可以指點迷津嗎 謝謝

### ISSUE THREAD

**Issue by hydesthydest** [reusu/FFXIVChnTextPatch#45]
不好意思，看來看去也沒看懂

所謂的會員就是要透過微信 or 支付保吧?

但我是海外無法用支付保，請問要如何使用微信付款呢?? 謝謝

**Comment by jxgzs** [comment]
打开 https://www.teemo.link
点击右上角 登陆 登入完之后点左上角 续约 选择你要续约的天书 点击续约 里面就有微信支付了

汉化---点击相关下载win客户端----解压打开TeemoClient---登陆账号密码---随便连接个就行---然后就可以打开FFXIVChnTextPatch进行汉化了---汉化完了就可以关了

**Comment by hydesthydest** [comment]
感謝 馬上來試試看!!!

> 打开 https://www.teemo.link
> 点击右上角--登陆--登入完之后点左上角续约---选择你要续约的天书 点击续约 里面就有微信支付了
> 
> 汉化---点击相关下载win客户端----解压打开TeemoClient---登陆账号密码---随便连接个就行---然后就可以打开FFXIVChnTextPatch进行汉化了---汉化完了就可以关了

**Comment by hydesthydest** [comment]
有請別人幫忙˙成功購買帳號(5 RMB)，再來我看到續約，時常意思是?  我看   36/30Days 請問是只能使用三十天的意思嗎  謝謝

**Comment by jxgzs** [comment]
如果你只是单纯的只想用汉化的话只要买30天的就好汉化完就可以不用了

hydesthydest <notifications@github.com> 于 2019年8月6日周二 13:23写道：

**Comment by royscf1209** [comment]
我購買30天的了，但登陸賬號密碼後，它連接不起來，連接狀態不斷的徘徊在正在連接--->正在斷開---->未連接

應該要如何解決

**Comment by royscf1209** [comment]
如圖所示
![disconnect](https://user-images.githubusercontent.com/53862806/62621681-1ce78280-b94f-11e9-8774-6dca28342955.jpg)
