### ISSUE TITLE
不好意思，還是無法付款......

### ISSUE THREAD

**Issue by hydesthydest** [reusu/FFXIVChnTextPatch#46]
因為沒有支付保，也無中國認定的銀行卡、信用卡可付微信
(我在台灣端，只能用國際信用卡......)

請問有任何帳號可以供充值嗎?  淘寶網店之類的可以支付......

不然真的想付錢但付不了阿......

謝謝

**Comment by hydesthydest** [comment]
無法付款......如下圖
https://imgur.com/a/fXeMU7h

**Comment by reusu** [comment]
海外仅支持wechat受款
敬请谅解
