### ISSUE TITLE
C2.3.0版本 傳送點選項顯示錯誤

### ISSUE THREAD

**Issue by m9sqq** [reusu/FFXIVChnTextPatch#48]
錯誤如下
![ffxiv_08122019_002822_581](https://user-images.githubusercontent.com/54002250/62836795-9ce85200-bc99-11e9-8ae8-3464a7bfc213.png)
![ffxiv_08122019_002835_053](https://user-images.githubusercontent.com/54002250/62836796-9f4aac00-bc99-11e9-838a-c0dd666800c8.png)

**Comment by reusu** [comment]
无复现
