### ISSUE TITLE
捉个虫哈

### ISSUE THREAD

**Issue by wingchaos** [reusu/FFXIVChnTextPatch#5]
任务-已完成-职业及特职任务-分类都乱了呀。。大地使者的内容却是战斗精英的。。如此类推。全乱了- -233333

**Comment by wingchaos** [comment]
还有哈。老哥，。像这种  exd/addon|11174|1它的内容呢是“<color #FFFF66>。。。。。。</color>”这样的。直接转换成base64 的话。。翻译后不会变颜色啊。有什么好方法方案哇。

**Comment by reusu** [comment]
自己可以研究一下HEXSTRING段的 02 13 开始03结尾的内容  
此段为颜色的特殊预留串
可以对应的写出自己想要的颜色串

**Comment by reusu** [comment]
分类错误是因为版本差异导致的
暂时无修改意向
因为中文版更新后就会一致
