### ISSUE TITLE
打本出現這些訊息後跳出

### ISSUE THREAD

**Issue by georgedora** [reusu/FFXIVChnTextPatch#6]
https://imgur.com/a/gu18O

**Comment by georgedora** [comment]
原本以為裝了正體才有這種訊息
結果轉回簡體才發現還是有機率性跳出

**Comment by reusu** [comment]
請注明副本名稱以及進度 謝謝合作 :)

**Comment by georgedora** [comment]
謝謝你！
目前遇到的狀況
繁體中文時：點選人物資訊裝備會跳出 / 軍團買賣材料會跳出
簡體中文時： 奧米加零式四樓 アースシェイカー時會跳出

**Comment by reusu** [comment]
繁中跳出的问题比较难解决
因为涉及到的内容较多
至于四层跳出应该已经FIX
