### ISSUE TITLE
一些漏掉的地方，emmmm

### ISSUE THREAD

**Issue by wingchaos** [reusu/FFXIVChnTextPatch#9]
チョコボかばん=陆行鸟背包
チョコボかばんから受け取る=从陆行鸟背包取回
チョコボかばんから受け取る（個数指定）=从陆行鸟背包取回指定数量
チョコボかばんに入れる=交给陆行鸟背包保管
チョコボかばんに入れる（個数指定）=交给陆行鸟背包保管指定数量

バーサクマスタリー=狂暴精通
コンテンツリプレイ=战斗回放
リプレイレディチェック=战斗回放确认
PvPチーム=PVP团队
シグマスケープ=西格玛幻晶
白虎のトーテム像=白虎图腾

**Comment by wingchaos** [comment]
ミラージュプレート選択=选择投影幻化方案
ミラージュプレート編集=编辑投影幻化方案
ミラージュプレート=投影幻化列表

ケナガウシステーキ=犏牛牛排
おでん=关东煮
グリーンリーキソテー=炒青韭菜
タコ焼き=章鱼烧
太巻き寿司=厚寿司卷
豆腐パンケーキ=豆腐煎饼
クリムゾンサイダー=深红苹果汁

**Comment by reusu** [comment]
目前汉化内容仅为副本相关
并且汉化的进度较慢
如果有兴趣的话可以加入到我们这里来
比较缺人手……
